### ISSUE TITLE
incorrect IBM Cloud Object Storage link to model assets

### ISSUE THREAD

**Issue by vabarbosa** [IBM/MAX-Image-Super-Resolution-Generator#1]
the [README](https://github.com/IBM/MAX-Image-Super-Resolution-Generator/blob/master/README.md) has the following link to where the models files are stored (IBM Cloud Object Storage):

- http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/max-image-super-resolution-generator/v1.0.0/assets.tar.gz

but that link fails! alternatively, the [Dockerfile](https://github.com/IBM/MAX-Image-Super-Resolution-Generator/blob/master/Dockerfile) has the link:

- http://max-assets.s3-api.us-geo.objectstorage.softlayer.net/max-image-super-resolution-generator/1.0/assets.tar.gz

which works.

**Comment by splovyt** [comment]
Of course! Thanks for noticing, I appreciate the feedback 🙂.

(fixed in [b2e04e4](https://github.com/IBM/MAX-Image-Super-Resolution-Generator/commit/b2e04e4f965e9b93e08fb7ac114df9c58b2f8ccd))

**Comment by ptitzler** [comment]
See https://github.ibm.com/CODAIT/Model-Asset-Exchange/issues/73

**Comment by splovyt** [comment]
> See https://github.ibm.com/CODAIT/Model-Asset-Exchange/issues/73

I updated our internal box note with the new endpoint, in addition to both my public models. Have the others seen this?

Thanks @ptitzler
